# 設定ファイルのバリデーションスキーマ
type: object
required:
  - app
  - pdf
  - test
  - logging
properties:
  app:
    type: object
    required:
      - name
      - version
    properties:
      name:
        type: string
      version:
        type: string
  
  pdf:
    type: object
    required:
      - output
    properties:
      output:
        type: object
        properties:
          directory:
            type: string
          format:
            type: string
            enum: [A4, A3, Letter, Legal]
          margin:
            type: string
          dpi:
            type: integer
            minimum: 72
            maximum: 1200
  
  test:
    type: object
    properties:
      timeout:
        type: integer
        minimum: 30000
      memory:
        type: object
        properties:
          limit:
            type: string
      options:
        type: object
        properties:
          runInBand:
            type: boolean
          detectOpenHandles:
            type: boolean
  
  logging:
    type: object
    properties:
      level:
        type: string
        enum: [debug, info, warn, error]
      format:
        type: string
        enum: [json, text]
